# Generated by Django 5.1.4 on 2024-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=20)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('SREQUEST', models.CharField(max_length=200)),
            ],
        ),
    ]
