# Generated by Django 5.1.4 on 2024-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('tname', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=40)),
                ('twitter', models.CharField(max_length=40)),
                ('instagram', models.CharField(max_length=40)),
            ],
        ),
    ]
