# Generated by Django 5.1.4 on 2024-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_technicians'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('cname', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
