# Generated by Django 5.1.4 on 2024-12-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK_CAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('DATE', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='image/')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('ADDERESS', models.CharField(max_length=300)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car_rent')),
            ],
        ),
    ]
