# Generated by Django 5.1.4 on 2024-12-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_title', models.CharField(max_length=50)),
                ('Icon', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
