# Generated by Django 5.1.4 on 2024-12-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ourservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservices',
            name='Icon',
        ),
    ]
