# Generated by Django 5.1.4 on 2025-01-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_datels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_car',
            old_name='ADDERESS',
            new_name='address',
        ),
        migrations.DeleteModel(
            name='datels',
        ),
        migrations.DeleteModel(
            name='OurServices',
        ),
    ]
