# Generated by Django 5.1.4 on 2025-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_adderess_book_car_address_delete_datels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_title', models.CharField(max_length=50)),
            ],
        ),
    ]
