# Generated by Django 5.1.4 on 2025-01-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ourservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='datels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=500)),
                ('point', models.CharField(max_length=100)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ourservices')),
            ],
        ),
    ]
