# Generated by Django 5.1.4 on 2025-01-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_datels'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('aname', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=10)),
            ],
        ),
    ]
