# Generated by Django 5.1.4 on 2025-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_car',
            name='file',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
