# Generated by Django 5.1.4 on 2025-01-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_book_car_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_car',
            old_name='file',
            new_name='img',
        ),
    ]
