# Generated by Django 5.1.4 on 2025-02-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_file_book_car_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNAME', models.CharField(max_length=20)),
                ('UEMAIL', models.EmailField(max_length=254)),
                ('PHONENO', models.CharField(max_length=10)),
                ('CAR_COMPANY', models.CharField(max_length=40)),
                ('CAR_MODEL', models.CharField(max_length=40)),
                ('STATE', models.CharField(max_length=40)),
                ('CITY', models.CharField(max_length=40)),
                ('ADDERESS', models.CharField(max_length=300)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accessories')),
            ],
        ),
    ]
