# Generated by Django 5.1.4 on 2025-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='singup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('c_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
