# Generated by Django 5.1.4 on 2025-03-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_singup_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singup',
            name='c_password',
        ),
    ]
