# Generated by Django 5.1.4 on 2025-03-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_singup_c_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories_deiails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('aname', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
