# Generated by Django 5.1.4 on 2025-03-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_accessories_deiails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accessories_deiails',
        ),
    ]
