# Generated by Django 5.1.4 on 2025-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datels',
            name='des',
            field=models.TextField(max_length=500),
        ),
    ]
