# Generated by Django 5.1.4 on 2025-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_datels_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datels',
            name='des',
            field=models.TextField(),
        ),
    ]
