# Generated by Django 5.1.4 on 2025-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_datels_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datels',
            name='point',
        ),
        migrations.AddField(
            model_name='datels',
            name='EmaiL',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
