# Generated by Django 5.1.4 on 2025-04-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_datels_point_datels_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datels',
            name='EmaiL',
            field=models.EmailField(max_length=254),
        ),
    ]
