# Generated by Django 5.1.4 on 2025-04-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_datels_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datels',
            name='EmaiL',
        ),
        migrations.AlterField(
            model_name='datels',
            name='image',
            field=models.ImageField(upload_to='...'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='H_title',
            field=models.CharField(max_length=100),
        ),
    ]
