# Generated by Django 5.1.4 on 2025-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_datels_email_alter_datels_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datels',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
