# Generated by Django 5.1.4 on 2025-04-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_datels_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='datels',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.services'),
            preserve_default=False,
        ),
    ]
