# Generated by Django 5.2 on 2025-04-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_datels_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datels',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='datels',
            name='sid',
        ),
    ]
