# Generated by Django 5.2 on 2025-04-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_datels_service_id_remove_datels_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datels',
            name='our_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datels', to='myapp.ourservices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myapp.datels'),
        ),
    ]
