# Generated by Django 5.2 on 2025-04-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_services_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datels',
            name='our_service',
        ),
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
