# Generated by Django 5.2 on 2025-04-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_datels_our_service_alter_services_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datels',
            name='Email',
        ),
    ]
